### ISSUE TITLE
Open in horizontal split

### ISSUE THREAD

**Issue by cd-a** [sodapopcan/vim-twiggy#40]
Is there a way to force it to open in horizontal split?

Like `rightbelow`?

I always have this layout

```
-----------
|    |    |
|    |    |
|    |    |
-----------
```

And it's a bit squishy for another vertical split

**Comment by sodapopcan** [comment]
For whatever reason, way back when I started this plugin, I decided I wanted to force it into a vertical split (I was modelling after the feel of NERDTree).  I'm perfectly fine to remove that restriction.  If you're vimscript savvy and feel so inclined to send a PR, I will happily accept.  Otherwise, I can fix this myself—I just need a couple of days to get to it.

**Comment by cd-a** [comment]
I don't have any experience in vimscript, but I'll give it a go :)
