### ISSUE TITLE
Branches buffer stays open when opening quickhelp buffer

### ISSUE THREAD

**Issue by yoyoyeti** [sodapopcan/vim-twiggy#9]
When I open Twiggy and then open the quickhelp menu from it I have one buffer for each thing.

**Comment by sodapopcan** [comment]
See #1 for previous discussion.

**Comment by yoyoyeti** [comment]
Alright, so I spent a bunch of time trying to figure out what in the world is going on with no luck. I tried removing all my plugins other than Twiggy and Fugitive, I tried commenting out all the other stuff I have set in my config, and I also tried it in vim instead of neovim. The problem still exists though. I'm all out of ideas.

**Comment by sodapopcan** [comment]
All good, I'll take a look!

**Comment by sodapopcan** [comment]
@lobstrr I got around to trying out your vimrc (or init.vim, as it were).  I have long since added the `bufhidden=delete` to twiggy and yeah, everything seems to work.  I tried checking out an older version that didn't have it but that produced problems I didn't care to delve into, heh.  So yeah, seems all good?  👍

**Comment by sodapopcan** [comment]
Hey @lobstrr, not sure if you ever tried this out or you are just continuing with your own fork but I thought I'd ping you one last time.
